title: NYU ACS Reading Group
description: Advanced Computer Science Topics & Discussion
url: "https://sentient_ramen.github.io/nyu-acs-website"
baseurl: "/nyu-acs-website"

# Jekyll theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
author:
  name: NYU ACS Reading Group
  email: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  topics:
    output: true
    permalink: /topics/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
