title: NYU ACS Reading Group
description: Advanced Computer Science Topics & Discussion
url: "https://nyu-acs.github.io/nyu-acs-website"
baseurl: "/nyu-acs-website"

# Jekyll theme
remote_theme: just-the-docs/just-the-docs
plugins:
- jekyll-remote-theme

# Site settings
author:
  name: NYU ACS Reading Group
  email: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Just the Docs theme settings
search_enabled: true
heading_anchors: true

# Navigation structure
nav_sort: case_insensitive

# Footer content
footer_content: "© 2025 NYU ACS Reading Group"

# Color scheme (optional)
color_scheme: light

# Collections
collections:
  topics:
    output: true
    permalink: /topics/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "default"
